var ad = '';
ad+="<link rel=\"StyleSheet\" href=\"css/style.css\" type=\"text/css\">";
ad+="<div id=\"add-wrapper\" />";
ad+="<canvas id=\"add\"> </canvas>";
ad+="<canvas id=\"sheet\"> </canvas>";
ad+="<canvas id=\"sheet_cont_1\"> </canvas>";
ad+="<canvas id=\"sheet_2\"> </canvas>";
ad+="<canvas id=\"sheet_cont_2\"> </canvas>";
ad+="<canvas id=\"sheet_3\"> </canvas>";
ad+="<canvas id=\"sheet_cont_3\"> </canvas>";
ad+="<canvas id=\"sheet_4\"> </canvas>";
ad+="<canvas id=\"sheet_cont_4\"> </canvas>";
ad+="<canvas id=\"caption_1\" style=\"visibility:hidden;opacity:0\"> </canvas>";
ad+="<canvas id=\"button-cta\"> </canvas>";
ad+="<canvas id=\"toplayer\"> </canvas>";
ad += "<"+"script type=\'text/javascript\' src=\"js/CSSPlugin.min.js\">\n";
ad += "<"+"/script>\n";
ad += "<"+"script type=\'text/javascript\' src=\"js/TweenLite.min.js\">\n";
ad += "<"+"/script>\n";
ad += "<"+"script type=\'text/javascript\' src=\"js/utils.js\">\n";
ad += "<"+"/script>\n";
ad += "<"+"script type=\'text/javascript\' src=\"customised/custom.js\">\n";
ad += "<"+"/script>\n";
ad += "<"+"script type=\'text/javascript\' src=\"js/main.js\">\n";
ad += "<"+"/script>\n";
ad+="</div>";
document.write(ad)
